### ISSUE TITLE
CSV Reader Error When Trying to Run rmsynthesis.py

### ISSUE THREAD

**Issue by catalyst995** [mrbell/pyrmsynth#20]
Hello all,

I recently installed pyrmsynth on my machine to analyse RM sources in my data, but when I try to run pyrmsynth on my data cubes, I get the following error:

rmsynthesis.py ver. 1.2.1
Written by Michael Bell

Parsing parameter file...
Traceback (most recent call last):
  File "/home/dpare/scripts/pyrmsynth/rmsynthesis.py", line 849, in <module>
    params = parse_input_file(args[0])
  File "/home/dpare/scripts/pyrmsynth/rmsynthesis.py", line 782, in parse_input_file
    for row in reader:
_csv.Error: line contains NULL byte

Is this an error with my images themselves or with their headers?  The images are 3D data cubes, which I think are what pyrmsynth takes as it's input, so I'm more inclined to think it's something with the image header which is causing rmsynthesis.py to throw this error.  However, I'm very unfamiliar with the details of the pyrmsynth code, so any advice as to what could be causing this issue is much appreciated.

Thank you very much.

**Comment by sarrvesh** [comment]
Hi,

It looks like the error is associated with the input parset file. Can you share your parset file and the command you used for calling rmsynthesis.py?

Cheers.

**Comment by catalyst995** [comment]
Hey sarrvesh.  I found the issue.  A stupid issue, really: I'd been trying to run pyrmsynth on the Q and U data images directly instead of giving it the parameter file.  It runs fine and I get great results when it receives the input rmsynth.par script.

Thank you very much for your assistance.

**Comment by sarrvesh** [comment]
Cool. Could you please close this ticket if this problem is resolved?
