### ISSUE TITLE
Error writing results to FITS files

### ISSUE THREAD

**Issue by duyhoang2014** [mrbell/pyrmsynth#23]
Hello Michael, Henrik,

I installed rmsysthesis. And the installation seems to indicate 'no' error.

$ python setup.py build_ext --inplace
running build_ext
skipping 'grid_tools.c' Cython extension (up-to-date)
$ python setup.py install --user
running install
running build
running build_py
running build_ext
skipping 'grid_tools.c' Cython extension (up-to-date)
running install_lib
running install_egg_info
Removing /home/hoang/.local/lib/python2.7/site-packages/rm_tools-1.2.1-py2.7.egg-info
Writing /home/hoang/.local/lib/python2.7/site-packages/rm_tools-1.2.1-py2.7.egg-info

But when running, rmsysthesis reports errors relating to writing the results to FITS files (Unexpected error: \<type 'exceptions.ValueError'\>). It could be the problem with input FITS files. However, when using rmsythesis on CEP3 (/home/horneffer/pyrmsynth/rmsynthesis.py), no such error is seen. Do you have ideas what could be the cause of the error in my installation? Below is the detail log.

$ python rmsynthesis.py rmsynthesis.parset -s
rmsynthesis.py ver. 1.3.0
Written by Michael Bell & Henrik Junklewitz

Parsing parameter file...
RM Synthesis parameters:
  Requested phi axis definition:
    phi_min:          -150.0
    dphi:             0.5
    nphi:             600
  Averaged spectral index provided:
    alpha:            False
    ref_freq:        Set to mean center frequency.
No image mask is specified. Will use all sky plane pixels                in RM Synthesis
  Polarized intensity detection threshold:  0.0
RM CLEAN not enabled
  Sky plane image limits:
    ra_lim:           [900, 1300]
    dec_lim:          [900, 1300]
  Reading from directory:  ./rm_in_post
  Writing to files starting with:  ./rm_out_post
 
-----------------------
 
Reading fits files into one big cube, converting Q & U to complex...
[====================] 100%

The maximum theroretical resolution for the given set of parameters is 31.0 rad/m^2
The maximum observable scale for the given set of parameters is 1.0 rad/m^2

RMSynth Initializing... Complete.
Done!
Performing synthesis...
[====================] 100%
RM synthesis done!  Writing out FITS files...
Warning: There was a problem generating the header, no header information stored!
Unexpected error: \<type 'exceptions.ValueError'\>
Warning: There was a problem generating the header, no header information stored!
Unexpected error: \<type 'exceptions.ValueError'\>
Warning: There was a problem generating the header, no header information stored!
Unexpected error: \<type 'exceptions.ValueError'\>
Computing polarized intensity and Faraday depth maps
Writing polarized intensity and Faraday depth maps
Warning: There was a problem generating the header, no header information stored!
Unexpected error: \<type 'exceptions.ValueError'\>
Warning: There was a problem generating the header, no header information stored!
Unexpected error: \<type 'exceptions.ValueError'\>
Warning: There was a problem generating the header, no header information stored!
Unexpected error: \<type 'exceptions.ValueError'\>
Warning: There was a problem generating the header, no header information stored!
Unexpected error: \<type 'exceptions.ValueError'\>
Cleaning up temp files...
Done!

Thanks,
Duy

**Comment by sarrvesh** [comment]
Hi Duy,

Thanks for reporting the bug. Can you let us know the version of your astropy?

- Sarrvesh

**Comment by duyhoang2014** [comment]
Hi Sarrvesh. It's astropy-1.2.1-py2.7-linux-x86_64.egg.

Duy

**Comment by sarrvesh** [comment]
Hi Duy,

I've found the bug and the problem is because some pyfits fits header functionality have changed in the recent versions. I've fixed it now. I will email you and @henrikju the correct rmsynthesis.py file. Just replace this file in your distribution and that should fix your problem.

Cheers,
Sarrvesh

**Comment by sarrvesh** [comment]
Once you confirm that the bug has been fixed, could you please close this ticket?

**Comment by duyhoang2014** [comment]
Thanks Sarrvesh. Yes, sure. I will try your suggestion when receiving the file. Is it possible to update the file on the repository or it is specific for different systems? Cheers, Duy

**Comment by duyhoang2014** [comment]
Nice. With the new msynthesis.py file, the problem solved! Thanks.
